export enum UIMapKey {
    MAP_CONDITIONALPOPUP = "MAP_CONDITIONALPOPUP",
    MAP_TRANSFER_POPUP = "MAP_TRANSFER_POPUP",
    MAP_BG_POPUP = "MAP_BG_POPUP",
    MAP_BOSS_FIRST_KILL = "MAP_BOSS_FIRST_KILL",
 }
